version: "3.9"
services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/
    env_file:
      - ./my_city/my_city/.env
    ports:
      - 5432:5432
    restart: unless-stopped

  api:
    build:
      context: .
      args:
        requirements_file: dev-requirements.txt
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./my_city/my_city/.env
    command: python my_city/manage.py runserver 0.0.0.0:8000
