# Generated by Django 4.1.6 on 2023-03-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_team_name'),
        ('quest_app', '0002_answertype_quest_alter_contact_contact_type_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='quest_app.quest', verbose_name='квест'),
        ),
        migrations.AlterField(
            model_name='category',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='user_app.team', verbose_name='участвующие команды'),
        ),
    ]
