# Generated by Django 4.1.6 on 2023-03-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0003_alter_category_name_alter_category_quest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='is_enumeration',
            field=models.BooleanField(default=False, verbose_name='признак ответа с перечислением'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='skip_symbols',
            field=models.CharField(blank=True, max_length=256, verbose_name='символы для пропуска в ответах юзеров'),
        ),
    ]
