# Generated by Django 4.1.6 on 2023-04-09 20:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='_team',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='_members',
                to='user_app.team',
                verbose_name='команда',
            ),
        ),
        migrations.AddField(
            model_name='member',
            name='member_number',
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name='номер участника в команде',
            ),
        ),
    ]
