# Generated by Django 4.1.6 on 2023-04-09 20:15

from django.db import migrations


def move_membership_to_participants(apps, _):
    team_model = apps.get_model('user_app', 'Team')
    member_model = apps.get_model('user_app', 'Member')

    for team in team_model.objects.all():
        members = team.members.all()
        for member in members:
            member.member_number = member.memberships.first().member_number
        member_model.objects.bulk_update(members, ['member_number'])
        members.update(_team=team)


class Migration(migrations.Migration):
    dependencies = [
        ('user_app', '0003_member__team_member_member_number'),
    ]

    operations = [
        migrations.RunPython(move_membership_to_participants),
    ]
