# Generated by Django 4.1.6 on 2023-03-11 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_team_name_alter_teammembership_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='в названии команды допускаются русские и английские буквы, цифры и пробелы если название содержит несколько слов', regex='^[ёЁа-яА-Я!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~\\w]+( [ёЁа-яА-Я!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~\\w]+)*$')], verbose_name='название команды'),
        ),
    ]
