# Generated by Django 4.1.8 on 2023-04-09 21:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20230409_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
        migrations.AlterField(
            model_name='member',
            name='_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='_members', to='user_app.team', verbose_name='команда'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='номер участника в команде'),
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
    ]
