# Generated by Django 4.1.8 on 2023-04-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_member_team_alter_member__team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='_team',
            new_name='team',
        ),
    ]
