# Generated by Django 4.1.8 on 2023-04-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_rename__team_member_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='user_app.team', verbose_name='команда'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('team', 'member_number')},
        ),
    ]
