name: Main

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make tests-ci
      - name: Run linter
        run: make lint-ci
      - name: Coveralls
        run: docker compose --file docker-compose.ci.yaml run -e COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }}  --rm api sh -c 'coverage run --source=my_city -m pytest my_city && coveralls --service=github'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}